[tool.poetry]
name = "ssss"
version = "0.0.0a1"
description = "ssss or super simple static site, a static site generator templated with jinja and markdown."
authors = ["Magnus Ã…berg <himself@magnusaberg.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
markdown = "^3.4.3"
staticjinja = "^4.1.3"
pyyaml = "^6.0"
argparse = "^1.4.0"

[tool.poetry.scripts]
ssss = "ssss:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
