[tool.poetry]
name = "ssss"
version = "0.0.0a3"
description = "ssss, short for Super Simple Static Site, is a static site generator that leverages Jinja and Markdown for creating templates and content. It generates static HTML files for an efficient and lightweight website."
authors = ["Magnus Ã…berg <himself@magnusaberg.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
markdown = "^3.4.3"
staticjinja = "^4.1.3"
pyyaml = "^6.0"
argparse = "^1.4.0"
importlib-metadata = "^6.3.0"

[tool.poetry.scripts]
ssss = "ssss:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
